### ISSUE TITLE
Brotli

### ISSUE THREAD

**Issue by petecooper** [textpattern/server-config#18]
NTS

**Comment by philwareham** [comment]
@petecooper just noticed that Brotli doesn't appear to be turned on for textpattern.com - anything we can do to rectify that?

**Comment by philwareham** [comment]
Cool, thanks Pete. Will look on in interest - no hurry, just thought it might of slipped through the net.

**Comment by petecooper** [comment]
Give me a week or so to wrap up the migration stuff and sanity checks, then we can take a look at this. We'll start with static compression, given the nature of our content, and we can look at dynamic when we know how that flies in real world terms.

**Comment by petecooper** [comment]
Brotli static now enabled on .com as a trial run.

**Comment by philwareham** [comment]
> Actually, scrap that. More work needed. Need to figure out best approach. Defer for now.

OK, no worries. Any chance you can share the Brotli module's config file for my own reference, or put it in the repo as a version controlled file? I'd like to see how it interacts with GZIP and what file types it targets.

I guess we can't simply use Cloudflare's Brotli compression as our origin server already GZIPs certain files - unless we disable  our GZIP? https://support.cloudflare.com/hc/en-us/articles/200168396

**Comment by petecooper** [comment]
As I understand it, and I've not had time (or inclination, honestly) to investigate too deeply yet:

* If you're running Brotli'd files on a server, you should really turn Gzip compression off.
* We have sites with dynamic content that's cached, and others with dynamic content that's raw.
* We have static content sites, which should also really be properly cached.

Reading up on Brotli, I will need to re-engineer the infra and Nginx setup to differentiate between all of the above…and then there's Cloudflare as an added gotcha…I will need to unlearn deploying Gzip as standard (which is engrained), and then rebuild the scaffold at a per-site level again. All doable, obviously, just not realistically in my near future with other work and life stuff causing complications.

Gut feeling says re-park this for now and I'll take a look when the days are a bit shorter. I do want to get my head around it, I just need a good on-ramp to get into the right mindset, and I'm out of practice after some months of offline chaos (which is bleeding into my online life in ways I'd rather it didn't). I'm in the process of putting my thing down, flipping it and reversing it to come at tasks from a different angle…it's just taking a while!

(Thanks for coming to my latest TED talk.)
