### ISSUE TITLE
Forum font loading denied by Access-Control-Allow-Origin rule

### ISSUE THREAD

**Issue by philwareham** [textpattern/server-config#22]
As the forum is still on .io domain, currently some browsers are denying access to the fonts cross-domain.

This rule in `www.textpattern.com.conf` is to blame:

    add_header Access-Control-Allow-Origin "https://*.textpattern.com";

My recommendation would be to migrate the forum rather than open the access control, or temporarily disable access control until the forum is on .com domain.

**Comment by philwareham** [comment]
For history see: https://forum.textpattern.io/viewtopic.php?id=49297

**Comment by philwareham** [comment]
Actually, looks like the font doesn't load in Firefox when on .com domain either. Maybe changing `https://*.textpattern.com` to `https://textpattern.com` might fix this?

**Comment by philwareham** [comment]
@petecooper just bumping this in case it was overlooked? Cheers!

**Comment by petecooper** [comment]
Will fix- didn't get any notification on this issue, weirdly.

**Comment by philwareham** [comment]
This is still an issue. See https://github.com/textpattern/server-config/issues/10
