### ISSUE TITLE
themes.textpattern.com not accessible from (.io) forum

### ISSUE THREAD

**Issue by philwareham** [textpattern/server-config#23]
When trying to access the 'themes' navigation tab from forum.textpattern.io there is a HSTS error in Firefox. Accessing it from the textpattern.com domain works as expected.

**Comment by petecooper** [comment]
This relates to a link mismatch outlined in 
https://github.com/textpattern/textpattern-forum/issues/224

@philwareham - let me know if we need a proper themes.textpattern.com site and I'll set the scaffolding up ASAP.

**Comment by petecooper** [comment]
Closing - OP issue resolved by @philwareham in 
https://github.com/textpattern/textpattern-forum/issues/224

**Comment by philwareham** [comment]
Cheers. I won't need the scaffold for a while yet.
