### ISSUE TITLE
Bare (www-less) domain for txpmag.com, textpattern.org & textpattern.net

### ISSUE THREAD

**Issue by petecooper** [textpattern/server-config#27]
@philwareham Per https://github.com/textile/textile-lang-com-website/issues/24, do you want bare domain only for txpmag.com, textpattern.org & textpattern.net?

**Comment by petecooper** [comment]
@philwareham Defer until after that action, or JFDI now?

**Comment by philwareham** [comment]
Ha ha - JFDI gets my vote always!

**Comment by petecooper** [comment]
Done - https://github.com/textpattern/server-config/commit/36c927a80cbdced3b7bea68916110b11e4d8763e
