### ISSUE TITLE
CSP `base-uri` rule

### ISSUE THREAD

**Issue by philwareham** [textpattern/server-config#34]
Although we don't use the `<base>` tag directly, we need to protect against malicious use of it.

Adding the following to our CSP will suffice:

    base-uri 'self'

See example commit: https://github.com/textpattern/server-config/commit/d10d031a99660a15beb60f80d4a0c622fe10273d

**Comment by petecooper** [comment]
Closing - see commit above. Thanks for the indent fixed @philwareham !
