### ISSUE TITLE
CSP `form-action` rule

### ISSUE THREAD

**Issue by philwareham** [textpattern/server-config#35]
We need to scour our code and check all `<form>` submissions are to self (which I would imagine they are). Then we can tighten CSP further with this rule:

    form-action 'self'

Note to self - check the way reCAPTCHA submits data on forum sign-up process.

**Comment by philwareham** [comment]
@petecooper @Bloke I've added this rule to our live forum's CSP and it all seems to work as normal still from my (albeit limited) testing. If people start notifying us there is a problem with the forum in next 24 hours we will know the rule will need loosening.

Just a note, in case! 🤞

**Comment by petecooper** [comment]
@philwareham - nice one. Please assign to me if/when you're happy stuff won't explode and I'll merge into other sites.

**Comment by philwareham** [comment]
I've added the `form-action` CSP rule into the forum config - happy for you to transfer into the other sites as I don't think it will cause a problem (I'll have to keep an eye on the RPC server and plugins sites though as I don't have source code of those to check against - up to you whether you include it in those to be honest).

**Comment by petecooper** [comment]
Done
