### ISSUE TITLE
Standardise SVG CSP

### ISSUE THREAD

**Issue by petecooper** [textpattern/server-config#36]
Provisional, needs further r&d/testing:

```
add_header Content-Security-Policy "default-src 'none'; style-src 'self' 'unsafe-inline'";
```

**Comment by petecooper** [comment]
@philwareham - additional brain requested…I think I've cracked it.

Based on the above provisional code, `default-src 'none'` should switch any CSP directive that's not explicitly mentioned to `none`, and the `style-src` should open up just that directive…right? That's some future-proofing with the `default-src` as a catch-all umbrella…right?

**Comment by philwareham** [comment]
Yes, that is generally correct. There are a few directives that don't automatically fallback to using the `default-src` though if not included - mostly where doing so would cause major breakages.

**Comment by petecooper** [comment]
Can you point me to a list of these, if there is one?

**Comment by philwareham** [comment]
I think the docs linked in my CSP state how a directive falls back (in blue box near top of document). For example: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/base-uri

**Comment by petecooper** [comment]
Done
