### ISSUE TITLE
Email announcement mailing list for new Textpattern version

### ISSUE THREAD

**Issue by petecooper** [textpattern/server-config#41]
Could be self-hosted (Mailtrain, Mautic et al) or third-party (Sendgrid, Mailchimp et al).

**Comment by philwareham** [comment]
I've used Mailchimp a few times in the past - as good as any. I would not be too keen on self-hosting anything that bulk emails - too many risks of server blacklisting IMO.

**Comment by petecooper** [comment]
If it was self-hosted, it would be a) on an entirely separate server and b) come with the trademark Cooper email hosting paranoia…

That said, I might talk nicely to some providers and see what I can arrange.

**Comment by petecooper** [comment]
Out of scope for now, closing.
