### ISSUE TITLE
Varnish HTTP cache (or similar)?

### ISSUE THREAD

**Issue by philwareham** [textpattern/server-config#45]
@petecooper Any worth in setting up a HTTP cache such as Varnish? Or have you already got a cache solution in place? Or not worth it for our (small) footprint? 

Just out of curiosity really.

Guide I found on Varnish for Nginx w/ Ubuntu: https://linuxconfig.org/how-to-install-varnish-cache-server-with-nginx-on-ubuntu-18-04-bionic-beaver-linux

**Comment by petecooper** [comment]
@philwareham Probably not worth it right now with the current footprint. It's something I'm doing A/B tests on elsewhere, but to be blunt I haven't found a Textpattern problem that needs solving with a cache. Varnish is a good call, but Nginx is already very good at static file serving, and for non-static elements, it has its own cache function.

So, gut feeling says defer until necessary, but please consider it on watch.

**Comment by philwareham** [comment]
Cool - sounds fine. The only reason I wondered is because one of my clients (using Drupal) have to use it (because of Drupal).

**Comment by petecooper** [comment]
>(because of Drupal)

Yeah, it's pretty much essential in Drupal's case. We'll be fine for now.
