### ISSUE TITLE
Expires Headers missing (on all but .com site).

### ISSUE THREAD

**Issue by philwareham** [textpattern/server-config#48]
The domain config files are missing expires headers (apart from the `www.textpattern.com` site). The following rules seem to be working satisfactorily so basically need to roll this out across all domains...

~~~
map $sent_http_content_type $www_textpattern_com_expires {
    application/atom+xml 1h;
    application/javascript 1M;
    application/json 0s;
    application/ld+json 0s;
    application/manifest+json 1w;
    application/rdf+xml 1h;
    application/rss+xml 1h;
    application/schema+json 0s;
    application/x-javascript 1M;
    application/xml 0s;
    font/woff 1y;
    font/woff2 1y;
    image/gif 1y;
    image/jpeg 1y;
    image/png 1y;
    image/svg+xml 1y;
    image/vnd.microsoft.icon 1M;
    image/webp 1y;
    image/x-icon 1M;
    text/cache-manifest 0s;
    text/css 1M;
    text/html 0s;
    text/javascript 1M;
    text/x-cross-domain-policy 1w;
    text/xml 3600s;
    video/mp4 1y;
    video/webm 1y;
    default 0s;
}
~~~

Note that once the sites are bedded in nicely we can extend the JS and CSS expire duration to 6M or 1y probably.

**Comment by petecooper** [comment]
Done, pending tests.

@philwareham - please put sites through the various wringers when time permits.

**Comment by philwareham** [comment]
Looking good...

Pingdom Tools
![pingdom-tools](https://user-images.githubusercontent.com/413665/58804402-b3bf5800-8609-11e9-8a6f-9141a963440b.png)

Google Pagespeed Insights - Desktop
![pagespeed-desktop](https://user-images.githubusercontent.com/413665/58804429-c20d7400-8609-11e9-90f9-e93f06eb98ac.png)

Google Pagespeed Insights - Mobile
![pagespeed-mobile](https://user-images.githubusercontent.com/413665/58804438-c9348200-8609-11e9-989d-db931f7393f0.png)

Think this can be closed now if this is on all domains now.

**Comment by petecooper** [comment]
Boom. Closing.
