### ISSUE TITLE
Sanity check plugins and themes CSP and FP headers

### ISSUE THREAD

**Issue by petecooper** [textpattern/server-config#55]
What connectivity to GitHub etc is required?

https://github.com/textpattern/server-config/blob/master/servers/files/trident.textpattern.com/etc/nginx/sites-available/plugins.textpattern.com.conf
https://github.com/textpattern/server-config/blob/master/servers/files/trident.textpattern.com/etc/nginx/sites-available/themes.textpattern.com.conf

**Comment by philwareham** [comment]
I don't think any special CSP is needed apart from *.textpattern.com cross-domain stuff. GitHub API is accessed server-side by PHP, not at user's end in-browser.

JS and CSS are from the main Textpattern.com site.

**Comment by petecooper** [comment]
OK, appears to be working - CSP activated on themes and plugins, please shout if anything not working.
