### ISSUE TITLE
default-theme.textpattern.com is down

### ISSUE THREAD

**Issue by petecooper** [textpattern/server-config#56]
Need to unpick and resurrect.

**Comment by philwareham** [comment]
I thought we had got rid of it in favour of the demo site?

**Comment by petecooper** [comment]
Hmm, maybe we did - I'll check the archives.

**Comment by petecooper** [comment]
Evidently we did!

https://github.com/textpattern/server-config/commit/e896f9d8ed1c83569bda70dea8c8dec450524816#diff-88af101bd2443893d675c53f49d1b78f901e0588aff514471875800dce82d938
