### ISSUE TITLE
CSP violation on Users panel

### ISSUE THREAD

**Issue by Bloke** [textpattern/server-config#57]
Operating the multi-edit action on the Users panel of the .com website (e.g. to 'Reset password') results in the browser console issuing:

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”).
```

No further info is supplied on which resource.

**Comment by philwareham** [comment]
FYI this can be made secure when we move to Textpattern 4.9 - as the CSP rules for Textpattern itself can be declared for via its config file. For now, the root will have to be less secure. Also see https://github.com/textpattern/server-config/issues/10

**Comment by Bloke** [comment]
It's got rid of the violation in the console, thanks. But still no Green message appears when performing a multi-edit action. Baffling!

**Comment by philwareham** [comment]
Force clear the cache? CSP rules stubbornly stay around.

**Comment by Bloke** [comment]
Still the same in an incognito window. Maybe the CSP rules persist there too?

**Comment by petecooper** [comment]
![Screenshot 2021-01-25 at 14 42 01](https://user-images.githubusercontent.com/226578/105720885-de1b0300-5f1b-11eb-9e4e-9f8d766b1f31.png)

Notification appears for the reset link, nothing shows on the reset password option and nothing in the console.

**Comment by petecooper** [comment]
![re](https://user-images.githubusercontent.com/226578/105721082-16224600-5f1c-11eb-9f46-e22960d013ca.png)

Notification does appear for the reset link, I get nothing on the reset password option and nothing in the console.
