### ISSUE TITLE
Branded maintenance / holding page

### ISSUE THREAD

**Issue by petecooper** [textpattern/server-config#59]
We currently use a *very* basic Tachyons-styled page for holding and maintenance when automatic builds etc warrant a temporary storefront. It would be more appropriate to have a Textpattern-styled holding page based on current patterns, perhaps with links to other network sites for the curious minds, ideally with some customisable text relating the site (e.g. design patterns etc).

@philwareham - is this viable?

**Comment by philwareham** [comment]
Sure, we can just link to the standard .com site's CSS and build a simple, specific HTML page for this purpose.

**Comment by petecooper** [comment]
Perfect, thanks. No rush.

**Comment by philwareham** [comment]
Can you let me know what this page should have on it, and when it is shown?

**Comment by petecooper** [comment]
Primarily it's used on sites that have a regular / scheduled rebuild from the respective repo, for the few seconds that stuff is being splatted and rebuilt.

Something akin to `https://textpattern.com/404.html` but with a "we'll be right back" message would be just fine, I think. Even the graphic works, unless you need an excuse to make another!

**Comment by petecooper** [comment]
…would also be useful when unexpected downtime happens so I don't have to scurry around when the pressure is on for a speedy resolution.

**Comment by philwareham** [comment]
I guess this will need its own CSS file yes, i.e. we can't link to the .com CSS file because that may be unavailable?

**Comment by petecooper** [comment]
As long as it's in a repo here (or elsewhere) then I can script it to be `curl`-d as needed, so a central copy is maintained and will roll out to our servers.

**Comment by philwareham** [comment]
How about this image, with a Textpattern logo and the text "We’ll be right back…" all in a small HTML page?... If yes then I'll supply today.

![emergency](https://user-images.githubusercontent.com/413665/108191443-0953d500-710b-11eb-90ae-41f1832a4fd2.png)

**Comment by petecooper** [comment]
Love it. Perfect. Thanks!

**Comment by Bloke** [comment]
Wow, that's fab!

**Comment by philwareham** [comment]
OK, there's a repo here with final page code in it: https://github.com/textpattern/emergency-broadcast-page

The `dist` directory can be either copied directly from `main` branch, or from the tagged release https://github.com/textpattern/emergency-broadcast-page/releases - whichever way you see fit. Cheers.

**Comment by philwareham** [comment]
[Example](https://textpattern.com/emergency-broadcast-page/)

**Comment by petecooper** [comment]
Closing – thanks very much @philwareham!
