### ISSUE TITLE
Update WOFF cross origin settings

### ISSUE THREAD

**Issue by petecooper** [textpattern/server-config#61]
```
location ~* \.(woff|woff2)$ {
    add_header Access-Control-Allow-Origin *;
}
```

See https://github.com/textpattern/server-config/issues/10#issuecomment-777626642

**Comment by petecooper** [comment]
Done and uploaded - @philwareham please sanity check when you have a moment and close / update issue as required. Thanks!

**Comment by philwareham** [comment]
Just done a scan on securotyheaders.com and that rule is in the green now :). Fonts seem to be working cross-domain too, so I'm happy to confirm this works. Closing. Thanks Pete!
