### ISSUE TITLE
Forum referrer-policy tighten?

### ISSUE THREAD

**Issue by philwareham** [textpattern/server-config#63]
Referring to this issue: https://fluxbb.org/forums/viewtopic.php?id=9860

Instead of `referrer-policy: strict-origin` which was found to be too strict, and `referrer-policy: origin-when-cross-origin` which I feel is too loose, can't we have?...

```
referrer-policy: strict-origin-when-cross-origin
```

I thought that is what we had working successfully in the forum on older server?

**Comment by petecooper** [comment]
See https://fluxbb.org/forums/viewtopic.php?id=9860

I'm not jazzed about it, honestly, but that's the only solution to the bad referrer error we were both getting.

**Comment by petecooper** [comment]
Oh hang on, I misread your OP. Leave that with me, I'll have a look.

**Comment by petecooper** [comment]
Done, committing now. For some reason I had no notification of this issue, wasn't ignoring it.

**Comment by philwareham** [comment]
Thanks - not saying it'll work but worth a try (I think that's what was et on the older server).

**Comment by petecooper** [comment]
>(I think that's what was set to on the older server)

It was, I hadn't had time to fully diff everything yet.
