### ISSUE TITLE
Cloudflare services

### ISSUE THREAD

**Issue by philwareham** [textpattern/server-config#64]
@petecooper @Bloke I want to start testing a select few of the Cloudflare services and how they'd improve global load times, starting soon (probably early May). To that end, there are a number of services that overlap with what we can provide on our servers directly (preferred route).

Just want to get your opinion on the following Cloudflare options:

1. Brotli compression (also see https://github.com/textpattern/server-config/issues/18).
2. HTML minification (I'd have to test this carefully and see if it has any issues with our HTML structure).
3. HTTP/3 (with QUIC).
4. 0-RTT Connection Resumption.
5. Onion Routing (Tor specific).

**Comment by petecooper** [comment]
>Brotli compression 

We can do this natively, I just haven't pushed it up the queue. I will.

>HTML minification

I'll defer to @philwareham - you're the pro!

>HTTP/3 (with QUIC).

This is due in Nginx in the coming months, please defer until summer.

>0-RTT Connection Resumption.

Conscious of replay attacks here, hence it's not enabled by us at the moment. Ongoing r&d.

>Onion Routing (Tor specific).

Can't really see the benefit, to be honest. We can easily spin up a .onion mirror locally, but that then becomes another domain property to maintain.

**Comment by philwareham** [comment]
Thanks Pete, so basically just the HTML minification (maybe) plus Cloudflare’s global caching would be the two features we’d use. Good to know.

**Comment by petecooper** [comment]
I'm not averse to the CDN aspect of things, no problem with that. I'd prefer to be 100% watertight with our own handling first so we're not _reliant_ on stuff Cloudflare offer. For example, I also have https://github.com/apache/incubator-pagespeed-ngx to look at, along with the other list of stuff.

…and I have to move house in 6 weeks. Busy few months!

**Comment by philwareham** [comment]
Good luck on the house move! Looking at the incubator-pagespeed-ngx repo - I don't think there's much in there we don't already do as part of our optimisation best practices. Again, it's mostly a band-aid for not doing those things ourselves, I feel.

I used to use the Apache version of the PageSpeed module when I had my own dedicated server, but that was yonks ago.

**Comment by petecooper** [comment]
Once the caching is set up and optimised / battle-tested, I think we're reaching the point of diminishing returns for overall performance improvements, though we can still tinker.

I'm going to try the HTTP/3 stuff on the demo servers first, I need to get a feel as to whether it's appropriate to jump to, given it's still very new and the benefits over HTTP/2. I have to understand the security aspects of it before deploying it at all, so bear with me on that. Timescales: we're reaching the end of the Nginx 1.19 branch, and I expect HTTP/3 to appear in Nginx core by 1.19.10 or 1.19.11 at this rate…which in real terms is going to be April or May, possibly June this year.

We should certainly bash heads on Brotli stuff after 4.8 has flown the roost as that looks like an easy win, and we might eke back ~10-15% judging by the things I've read.

**Comment by philwareham** [comment]
Cheers Pete - sounds good. Regarding HTML minification, it would could such a tiny performance gains it's hardly worth it - but I'll test anyway.

The biggest gain now apart from Brotli would be to use Cloudflare's CDN. Although that'll make hardly any difference in Europe where are servers are located (in fact, in my limited testing it was a few milliseconds _slower_), it _should_ greatly improve load times at geographically distant locations. i.e. testing with Pingdom Tools via their Australia instance, the load time is around 2 seconds (compared to ~250ms when using a Europe instance). Most of that is wait time while the server is reached.

**Comment by petecooper** [comment]
Leave it a week if you can, the AMD + NVMe server I'm using for .com (plus other stuff) will be in San Francisco, availability isn't 100% across DO datacenters so it's a good opportunity to move a server out of Europe *and* test CDN stuff. That's schedule to move this week with no downtime, so if we can defer the CDN stuff until at least this time next week, you should have "good" servers to test against.

**Comment by philwareham** [comment]
Of course - it won't be until after 10th May due to the upcoming [Cloudflare Cookie removal](https://blog.cloudflare.com/deprecating-cfduid-cookie/). Thanks again Pete, love the server work!
