### ISSUE TITLE
Use DNS records for Bing/Google/Yandex verification

### ISSUE THREAD

**Issue by philwareham** [textpattern/server-config#65]
Currently we have HTML verification files per domain in each root folder of our family of sites. Should we use the DNS records option instead, to simplify the process and tidy the repos up slightly? Just getting opinions for/against.

**Comment by Bloke** [comment]
It's certainly neater so if we can do it, then yes it makes more sense than the manual verification method.

**Comment by petecooper** [comment]
DNS, I can't abide filesystem litter.

**Comment by petecooper** [comment]
Please go ahead with this - should be easy enough with Cloudflare. Make sure you export the latest DNS entries after you've done it, and I'll be a happy bunny.

**Comment by philwareham** [comment]
It's already done - but where do you want me to export the DNS entries to?

**Comment by petecooper** [comment]
https://github.com/textpattern/server-config/tree/main/dns - please and thanks.

**Comment by philwareham** [comment]
Done (it was already done months ago actually 😂)
