### ISSUE TITLE
Process everything in `_todo` then delete

### ISSUE THREAD

**Issue by petecooper** [textpattern/server-config#66]
NTS: sift through everything in `_todo` for nuggets of wisdom, then remove.

@philwareham – no need to edit anything in there, most of it is legacy stuff and I'll work through it as a background task.

**Comment by philwareham** [comment]
I think the old config files were in a fairly tidy state - I'd skimmed the CSP and Feature Policy stuff recently and they were in good shaper and consistent. So nothing from me at this point, thanks.
