### ISSUE TITLE
Plugins site - images fetched by `data:` are being blocked by CSP

### ISSUE THREAD

**Issue by philwareham** [textpattern/server-config#76]
There are images missing on the plugins.textpattern.com website. Seems to be something up with the CSP rules around `img-src` but looking through the config files here on GitHub I can't see an obvious reason why (unless these files differ from what is actually in the server?).

**Comment by petecooper** [comment]
@philwareham Just saw this, didn't get any notification - I'll investigate.

**Comment by petecooper** [comment]
Seems to be working - closing for now.
